# Generated by Django 2.0.1 on 2018-01-24 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this story', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Story Title', max_length=40)),
                ('story', models.TextField(help_text='Please tell us about why people are awesome', max_length=1000)),
                ('Date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
