# Generated by Django 2.0.1 on 2018-05-12 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the product', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='price of product', max_digits=5)),
                ('photo', models.ImageField(upload_to='image\\product')),
                ('description', models.TextField(help_text='Description of the product', max_length=1000)),
                ('checkout_button', models.CharField(help_text='variable to hold paypal button', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this story', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Story Title', max_length=40)),
                ('story', models.TextField(help_text='Please tell us why people are awesome', max_length=3000)),
                ('Date_added', models.DateField(auto_now_add=True, null=True)),
                ('photo', models.ImageField(upload_to='image')),
                ('featured', models.BooleanField(default=False)),
                ('photo_height', models.CharField(help_text='height of photo', max_length=8)),
                ('photo_width', models.CharField(help_text='height of photo', max_length=8)),
                ('top', models.CharField(help_text='center of the photo', max_length=20)),
                ('left', models.CharField(help_text='center of the photo', max_length=20)),
                ('Author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
