# Generated by Django 2.0.1 on 2018-06-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='left',
        ),
        migrations.RemoveField(
            model_name='story',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='story',
            name='photo_width',
        ),
        migrations.RemoveField(
            model_name='story',
            name='top',
        ),
    ]
