# Generated by Django 2.0.1 on 2018-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='Date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
