# Generated by Django 2.0.1 on 2018-03-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180227_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(help_text='Please tell us why people are awesome', max_length=1000),
        ),
    ]
