# Generated by Django 2.0.1 on 2018-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180305_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(help_text='Please tell us why people are awesome', max_length=3000),
        ),
    ]
