# Generated by Django 2.0.1 on 2018-04-08 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180307_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Name of the product', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='price of product', max_digits=5)),
                ('photo', models.ImageField(upload_to='image\\product')),
                ('description', models.TextField(help_text='Description of the product', max_length=1000)),
            ],
        ),
    ]
