# Generated by Django 2.0.1 on 2018-04-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
