# Generated by Django 2.0.1 on 2018-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_checkout_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='photo_height',
            field=models.CharField(default=200, help_text='height of photo', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='photo_width',
            field=models.CharField(default=200, help_text='height of photo', max_length=8),
            preserve_default=False,
        ),
    ]
