# Generated by Django 2.0.1 on 2018-04-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180419_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='left',
            field=models.CharField(default=1, help_text='center of the photo', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='top',
            field=models.CharField(default=1, help_text='center of the photo', max_length=8),
            preserve_default=False,
        ),
    ]
