# Generated by Django 2.0.1 on 2018-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180420_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='left',
            field=models.CharField(help_text='center of the photo', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='top',
            field=models.CharField(help_text='center of the photo', max_length=20),
        ),
    ]
