# Generated by Django 2.0.1 on 2018-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180421_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
