# Generated by Django 2.0.1 on 2018-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20180421_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='photo',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
