# Generated by Django 2.0.1 on 2018-05-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180421_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='featured',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
