# Generated by Django 2.0.1 on 2018-05-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20180501_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
