# Generated by Django 2.0.1 on 2018-05-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20180504_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='featured',
        ),
    ]
