# Generated by Django 2.0.1 on 2018-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_story_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
