# Generated by Django 2.0.1 on 2018-05-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_story_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='orientation',
        ),
    ]
